use intranet;
## INSERT TABLE CATEGORIA
INSERT INTO CATEGORIA VALUES(1,'Administrador');
INSERT INTO CATEGORIA VALUES(2,'Funcionário');
INSERT INTO CATEGORIA VALUES(3,'Aluno');

## INSERT TABLE FUNCAO
INSERT INTO FUNCAO VALUES(1,'Diretor');
INSERT INTO FUNCAO VALUES(2,'Professor');
INSERT INTO FUNCAO VALUES(3,'Aluno');

## INSERT TABLE PESSOA
INSERT INTO PESSOA VALUES(1,'Wellinton', 'Perazzoli', '1993/10/02', 1);
INSERT INTO PESSOA VALUES(2,'Camila', 'Lemes', '1995/03/04', 1);

INSERT INTO PESSOA VALUES(3,'Kurosaki', 'Ichigo', '1993/03/07', 2);
INSERT INTO PESSOA VALUES(4,'Raito', 'Agami', '1990/05/07', 2);

INSERT INTO PESSOA VALUES(5,'Aluno 1', 'aluno 1', '1990/05/07', 3);
INSERT INTO PESSOA VALUES(6,'Aluno 2', 'aluno 2', '1990/05/07', 3);
INSERT INTO PESSOA VALUES(7,'Aluno 3', 'aluno 3', '1990/05/07', 3);
INSERT INTO PESSOA VALUES(8,'Aluno 4', 'aluno 4', '1990/05/07', 3);
INSERT INTO PESSOA VALUES(9,'Aluno 5', 'aluno 5', '1990/05/07', 3);
INSERT INTO PESSOA VALUES(10,'Aluno 6', 'aluno 6', '1990/05/07', 3);

## INSERT TABLE USUARIO
INSERT INTO USUARIO VALUES(1,'wellctba@gmail.com','well123',1,1);
INSERT INTO USUARIO VALUES(2,'camilabeatriz@msn.com','misty123',2,1);

INSERT INTO USUARIO VALUES(3,'kurosakiichigo@gmail.com','kuro123',3,2);
INSERT INTO USUARIO VALUES(4, 'raito@hotmail.com','raito123',4,2);

INSERT INTO USUARIO VALUES(5, 'aluno1@hotmail.com','raito123',5,3);
INSERT INTO USUARIO VALUES(6, 'aluno2@hotmail.com','raito123',6,3);
INSERT INTO USUARIO VALUES(7, 'aluno3@hotmail.com','raito123',7,3);
INSERT INTO USUARIO VALUES(8, 'aluno4@hotmail.com','raito123',8,3);
INSERT INTO USUARIO VALUES(9, 'aluno5@hotmail.com','raito123',9,3);
INSERT INTO USUARIO VALUES(10, 'aluno6@hotmail.com','raito123',10,3);



## INSERT TABLE TURMA
INSERT INTO TURMA VALUES(1, 'INFANTIL 1', 'INTEGRAL');
INSERT INTO TURMA VALUES(2, 'INFANTIL 1', 'MEIO PERIODO');
INSERT INTO TURMA VALUES(3, 'INFANTIL 2', 'INTEGRAL');

## INSERT TABLE DISCIPLINA
INSERT INTO DISCIPLINA VALUES(1, 'Matemática 1', 1);
INSERT INTO DISCIPLINA VALUES(2, 'Matemática 1', 2);
INSERT INTO DISCIPLINA VALUES(3, 'Matemática 2', 3);

## INSERT TABLE USUARIO
INSERT INTO PESSOA_DISCIPLINA VALUES(3,1);
INSERT INTO PESSOA_DISCIPLINA VALUES(3,2);
INSERT INTO PESSOA_DISCIPLINA VALUES(4,3);

INSERT INTO PESSOA_DISCIPLINA VALUES(5,1);
INSERT INTO PESSOA_DISCIPLINA VALUES(6,1);
INSERT INTO PESSOA_DISCIPLINA VALUES(7,2);
INSERT INTO PESSOA_DISCIPLINA VALUES(8,2);
INSERT INTO PESSOA_DISCIPLINA VALUES(9,3);
INSERT INTO PESSOA_DISCIPLINA VALUES(10,3);